/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.esenzioniservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-12T06:40:10.716+02:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "EsenzioniService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EsenzioniService {

    @WebMethod
    @WebResult(name = "getEsenzioniResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getEsenzioniResponse")
    public EsenzioniResponse getEsenzioni(

        @WebParam(partName = "getEsenzioni", name = "getEsenzioni", targetNamespace = "http://dmacc.csi.it/")
        EsenzioniRequest getEsenzioni
    );
}
