/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.verificaservices.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-07-08T14:49:45.743+02:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "VerificaService")
@XmlSeeAlso({it.csi.dma.apiopsan.verificaservices.dma.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VerificaService {

    @WebMethod
    @WebResult(name = "verificaOscuramentoDocResponse", targetNamespace = "http://dmacc.csi.it/", partName = "verificaOscuramentoDocResponse")
    public VerificaOscuramentoDocResponse verificaOscuramentoDoc(

        @WebParam(partName = "verificaOscuramentoDoc", name = "verificaOscuramentoDoc", targetNamespace = "http://dmacc.csi.it/")
        VerificaOscuramentoDocRequest verificaOscuramentoDoc
    );

    @WebMethod
    @WebResult(name = "verificaPinResponse", targetNamespace = "http://dmacc.csi.it/", partName = "verificaPinResponse")
    public VerificaPinResponse verificaPin(

        @WebParam(partName = "verificaPin", name = "verificaPin", targetNamespace = "http://dmacc.csi.it/")
        VerificaPinRequest verificaPin
    );

    @WebMethod
    @WebResult(name = "verificaUtenteAbilitatoResponse", targetNamespace = "http://dmacc.csi.it/", partName = "verificaUtenteAbilitatoResponse")
    public VerificaUtenteAbilitatoResponse verificaUtenteAbilitato(

        @WebParam(partName = "verificaUtenteAbilitato", name = "verificaUtenteAbilitato", targetNamespace = "http://dmacc.csi.it/")
        VerificaUtenteAbilitatoRequest verificaUtenteAbilitato
    );
}
