/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.verificaservices.dmacc;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-07-08T14:49:45.751+02:00
 * Generated source version: 3.5.3
 *
 */


@WebServiceClient(name = "VerificaService",
                  wsdlLocation = "",
                  targetNamespace = "http://dmacc.csi.it/")
public class VerificaService_Service extends Service {

	
    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "VerificaService");
    public final static QName VerificaServicePort = new QName("http://dmacc.csi.it/", "VerificaServicePort");
    static {
        URL url = null;
        try {
            url = new URL("");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VerificaService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "VerificaService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VerificaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VerificaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerificaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public VerificaService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VerificaService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VerificaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns VerificaService
     */
    @WebEndpoint(name = "VerificaServicePort")
    public VerificaService getVerificaServicePort() {
        return super.getPort(VerificaServicePort, VerificaService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerificaService
     */
    @WebEndpoint(name = "VerificaServicePort")
    public VerificaService getVerificaServicePort(WebServiceFeature... features) {
        return super.getPort(VerificaServicePort, VerificaService.class, features);
    }

}
