/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.csi.dma.apiopsan.verificaservices.dmacc;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-07-08T14:49:45.727+02:00
 * Generated source version: 3.5.3
 *
 */

@javax.jws.WebService(
                      serviceName = "VerificaService",
                      portName = "VerificaServicePort",
                      targetNamespace = "http://dmacc.csi.it/",
                      wsdlLocation = "",
                      endpointInterface = "it.csi.dma.apiopsan.verificaservices.dmacc.VerificaService")

public class VerificaServicePortImpl implements VerificaService {

    private static final Logger LOG = Logger.getLogger(VerificaServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see it.csi.dmacc.VerificaService#verificaOscuramentoDoc(it.csi.dmacc.VerificaOscuramentoDocRequest verificaOscuramentoDoc)*
     */
    public it.csi.dma.apiopsan.verificaservices.dmacc.VerificaOscuramentoDocResponse verificaOscuramentoDoc(VerificaOscuramentoDocRequest verificaOscuramentoDoc) {
        LOG.info("Executing operation verificaOscuramentoDoc");
        System.out.println(verificaOscuramentoDoc);
        try {
            it.csi.dma.apiopsan.verificaservices.dmacc.VerificaOscuramentoDocResponse _return = new it.csi.dma.apiopsan.verificaservices.dmacc.VerificaOscuramentoDocResponse();
            java.util.List<it.csi.dma.apiopsan.verificaservices.dmacc.Errore> _returnErrori = new java.util.ArrayList<it.csi.dma.apiopsan.verificaservices.dmacc.Errore>();
            it.csi.dma.apiopsan.verificaservices.dmacc.Errore _returnErroriVal1 = new it.csi.dma.apiopsan.verificaservices.dmacc.Errore();
            _returnErroriVal1.setCodice("Codice-1582253669");
            _returnErroriVal1.setDescrizione("Descrizione-277387855");
            _returnErrori.add(_returnErroriVal1);
            _return.getErrori().addAll(_returnErrori);
            it.csi.dma.apiopsan.verificaservices.dmacc.RisultatoCodice _returnEsito = it.csi.dma.apiopsan.verificaservices.dmacc.RisultatoCodice.FALLIMENTO;
            _return.setEsito(_returnEsito);
            it.csi.dma.apiopsan.verificaservices.dma.DatiDocumentoResponse _returnDatiDocumentoResponse = new it.csi.dma.apiopsan.verificaservices.dma.DatiDocumentoResponse();
            _returnDatiDocumentoResponse.setCodCL("CodCL1310157132");
            _returnDatiDocumentoResponse.setCodDocumentoDipartimentale("CodDocumentoDipartimentale560773548");
            _returnDatiDocumentoResponse.setIdDocumentoIlec("IdDocumentoIlec61746410");
            _returnDatiDocumentoResponse.setOscurato("Oscurato-1487586496");
            _return.setDatiDocumentoResponse(_returnDatiDocumentoResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.dmacc.VerificaService#verificaPin(it.csi.dmacc.VerificaPinRequest verificaPin)*
     */
    public it.csi.dma.apiopsan.verificaservices.dmacc.VerificaPinResponse verificaPin(VerificaPinRequest verificaPin) {
        LOG.info("Executing operation verificaPin");
        System.out.println(verificaPin);
        try {
            it.csi.dma.apiopsan.verificaservices.dmacc.VerificaPinResponse _return = new it.csi.dma.apiopsan.verificaservices.dmacc.VerificaPinResponse();
            java.util.List<it.csi.dma.apiopsan.verificaservices.dmacc.Errore> _returnErrori = new java.util.ArrayList<it.csi.dma.apiopsan.verificaservices.dmacc.Errore>();
            it.csi.dma.apiopsan.verificaservices.dmacc.Errore _returnErroriVal1 = new it.csi.dma.apiopsan.verificaservices.dmacc.Errore();
            _returnErroriVal1.setCodice("Codice960154241");
            _returnErroriVal1.setDescrizione("Descrizione392626724");
            _returnErrori.add(_returnErroriVal1);
            _return.getErrori().addAll(_returnErrori);
            it.csi.dma.apiopsan.verificaservices.dmacc.RisultatoCodice _returnEsito = it.csi.dma.apiopsan.verificaservices.dmacc.RisultatoCodice.FALLIMENTO;
            _return.setEsito(_returnEsito);
            it.csi.dma.apiopsan.verificaservices.dma.DatiDocumentoResponse _returnDatiDocumentoResponse = new it.csi.dma.apiopsan.verificaservices.dma.DatiDocumentoResponse();
            _returnDatiDocumentoResponse.setCodCL("CodCL1516323159");
            _returnDatiDocumentoResponse.setCodDocumentoDipartimentale("CodDocumentoDipartimentale-1933297250");
            _returnDatiDocumentoResponse.setIdDocumentoIlec("IdDocumentoIlec-295531879");
            _returnDatiDocumentoResponse.setOscurato("Oscurato-1935918961");
            _return.setDatiDocumentoResponse(_returnDatiDocumentoResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.dmacc.VerificaService#verificaUtenteAbilitato(it.csi.dmacc.VerificaUtenteAbilitatoRequest verificaUtenteAbilitato)*
     */
    public it.csi.dma.apiopsan.verificaservices.dmacc.VerificaUtenteAbilitatoResponse verificaUtenteAbilitato(VerificaUtenteAbilitatoRequest verificaUtenteAbilitato) {
        LOG.info("Executing operation verificaUtenteAbilitato");
        System.out.println(verificaUtenteAbilitato);
        try {
            it.csi.dma.apiopsan.verificaservices.dmacc.VerificaUtenteAbilitatoResponse _return = new it.csi.dma.apiopsan.verificaservices.dmacc.VerificaUtenteAbilitatoResponse();
            java.util.List<it.csi.dma.apiopsan.verificaservices.dmacc.Errore> _returnErrori = new java.util.ArrayList<it.csi.dma.apiopsan.verificaservices.dmacc.Errore>();
            it.csi.dma.apiopsan.verificaservices.dmacc.Errore _returnErroriVal1 = new it.csi.dma.apiopsan.verificaservices.dmacc.Errore();
            _returnErroriVal1.setCodice("Codice-1079881107");
            _returnErroriVal1.setDescrizione("Descrizione401185489");
            _returnErrori.add(_returnErroriVal1);
            _return.getErrori().addAll(_returnErrori);
            it.csi.dma.apiopsan.verificaservices.dmacc.RisultatoCodice _returnEsito = it.csi.dma.apiopsan.verificaservices.dmacc.RisultatoCodice.FALLIMENTO;
            _return.setEsito(_returnEsito);
            java.util.List<it.csi.dma.apiopsan.verificaservices.dmacc.Codifica> _returnListaProfili = new java.util.ArrayList<it.csi.dma.apiopsan.verificaservices.dmacc.Codifica>();
            it.csi.dma.apiopsan.verificaservices.dmacc.Codifica _returnListaProfiliVal1 = new it.csi.dma.apiopsan.verificaservices.dmacc.Codifica();
            _returnListaProfiliVal1.setCodice("Codice-1636463630");
            _returnListaProfiliVal1.setDescrizione("Descrizione-510331758");
            _returnListaProfili.add(_returnListaProfiliVal1);
            _return.getListaProfili().addAll(_returnListaProfili);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
