/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


package it.csi.dma.apiopsan.verificaservices.dmacc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-07-08T14:49:45.633+02:00
 * Generated source version: 3.5.3
 *
 */
public final class VerificaService_VerificaServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://dmacc.csi.it/", "VerificaService");

    private VerificaService_VerificaServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VerificaService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        VerificaService_Service ss = new VerificaService_Service(wsdlURL, SERVICE_NAME);
        VerificaService port = ss.getVerificaServicePort();

        {
        System.out.println("Invoking verificaOscuramentoDoc...");
        it.csi.dma.apiopsan.verificaservices.dmacc.VerificaOscuramentoDocRequest _verificaOscuramentoDoc_verificaOscuramentoDoc = new it.csi.dma.apiopsan.verificaservices.dmacc.VerificaOscuramentoDocRequest();
        it.csi.dma.apiopsan.verificaservices.dma.RichiedenteInfo _verificaOscuramentoDoc_verificaOscuramentoDocRichiedente = new it.csi.dma.apiopsan.verificaservices.dma.RichiedenteInfo();
        it.csi.dma.apiopsan.verificaservices.dmacc.ApplicativoVerticale _verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteApplicativoVerticale = new it.csi.dma.apiopsan.verificaservices.dmacc.ApplicativoVerticale();
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteApplicativoVerticale.setCodice("Codice412198750");
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteApplicativoVerticale.setDescrizione("Descrizione-180981427");
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedente.setApplicativoVerticale(_verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteApplicativoVerticale);
        it.csi.dma.apiopsan.verificaservices.dmacc.ApplicazioneRichiedente _verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteApplicazione = new it.csi.dma.apiopsan.verificaservices.dmacc.ApplicazioneRichiedente();
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteApplicazione.setCodice("Codice-1239145397");
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteApplicazione.setDescrizione("Descrizione-1099903697");
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedente.setApplicazione(_verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteApplicazione);
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedente.setCodiceFiscale("CodiceFiscale509469172");
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedente.setIp("Ip2014519361");
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedente.setNumeroTransazione("NumeroTransazione-1049423090");
        it.csi.dma.apiopsan.verificaservices.dma.Ruolo _verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteRuolo = new it.csi.dma.apiopsan.verificaservices.dma.Ruolo();
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteRuolo.setCodice("Codice-1388868845");
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteRuolo.setDescrizione("Descrizione1014012779");
        _verificaOscuramentoDoc_verificaOscuramentoDocRichiedente.setRuolo(_verificaOscuramentoDoc_verificaOscuramentoDocRichiedenteRuolo);
        _verificaOscuramentoDoc_verificaOscuramentoDoc.setRichiedente(_verificaOscuramentoDoc_verificaOscuramentoDocRichiedente);
        it.csi.dma.apiopsan.verificaservices.dma.DatiDocumento _verificaOscuramentoDoc_verificaOscuramentoDocDatiDocumento = new it.csi.dma.apiopsan.verificaservices.dma.DatiDocumento();
        _verificaOscuramentoDoc_verificaOscuramentoDocDatiDocumento.setCodCL("CodCL-915846079");
        _verificaOscuramentoDoc_verificaOscuramentoDocDatiDocumento.setCodDocumentoDipartimentale("CodDocumentoDipartimentale774928143");
        _verificaOscuramentoDoc_verificaOscuramentoDocDatiDocumento.setIdDocumentoIlec("IdDocumentoIlec963167689");
        _verificaOscuramentoDoc_verificaOscuramentoDocDatiDocumento.setPin("Pin-1690620514");
        _verificaOscuramentoDoc_verificaOscuramentoDoc.setDatiDocumento(_verificaOscuramentoDoc_verificaOscuramentoDocDatiDocumento);
        it.csi.dma.apiopsan.verificaservices.dmacc.VerificaOscuramentoDocResponse _verificaOscuramentoDoc__return = port.verificaOscuramentoDoc(_verificaOscuramentoDoc_verificaOscuramentoDoc);
        System.out.println("verificaOscuramentoDoc.result=" + _verificaOscuramentoDoc__return);


        }
        {
        System.out.println("Invoking verificaPin...");
        it.csi.dma.apiopsan.verificaservices.dmacc.VerificaPinRequest _verificaPin_verificaPin = new it.csi.dma.apiopsan.verificaservices.dmacc.VerificaPinRequest();
        it.csi.dma.apiopsan.verificaservices.dma.RichiedenteInfo _verificaPin_verificaPinRichiedente = new it.csi.dma.apiopsan.verificaservices.dma.RichiedenteInfo();
        it.csi.dma.apiopsan.verificaservices.dmacc.ApplicativoVerticale _verificaPin_verificaPinRichiedenteApplicativoVerticale = new it.csi.dma.apiopsan.verificaservices.dmacc.ApplicativoVerticale();
        _verificaPin_verificaPinRichiedenteApplicativoVerticale.setCodice("Codice20140931");
        _verificaPin_verificaPinRichiedenteApplicativoVerticale.setDescrizione("Descrizione582887853");
        _verificaPin_verificaPinRichiedente.setApplicativoVerticale(_verificaPin_verificaPinRichiedenteApplicativoVerticale);
        it.csi.dma.apiopsan.verificaservices.dmacc.ApplicazioneRichiedente _verificaPin_verificaPinRichiedenteApplicazione = new it.csi.dma.apiopsan.verificaservices.dmacc.ApplicazioneRichiedente();
        _verificaPin_verificaPinRichiedenteApplicazione.setCodice("Codice1021752619");
        _verificaPin_verificaPinRichiedenteApplicazione.setDescrizione("Descrizione-1269106695");
        _verificaPin_verificaPinRichiedente.setApplicazione(_verificaPin_verificaPinRichiedenteApplicazione);
        _verificaPin_verificaPinRichiedente.setCodiceFiscale("CodiceFiscale1213736410");
        _verificaPin_verificaPinRichiedente.setIp("Ip492574869");
        _verificaPin_verificaPinRichiedente.setNumeroTransazione("NumeroTransazione1426293733");
        it.csi.dma.apiopsan.verificaservices.dma.Ruolo _verificaPin_verificaPinRichiedenteRuolo = new it.csi.dma.apiopsan.verificaservices.dma.Ruolo();
        _verificaPin_verificaPinRichiedenteRuolo.setCodice("Codice1520876676");
        _verificaPin_verificaPinRichiedenteRuolo.setDescrizione("Descrizione2141026160");
        _verificaPin_verificaPinRichiedente.setRuolo(_verificaPin_verificaPinRichiedenteRuolo);
        _verificaPin_verificaPin.setRichiedente(_verificaPin_verificaPinRichiedente);
        it.csi.dma.apiopsan.verificaservices.dma.DatiDocumento _verificaPin_verificaPinDatiDocumento = new it.csi.dma.apiopsan.verificaservices.dma.DatiDocumento();
        _verificaPin_verificaPinDatiDocumento.setCodCL("CodCL2026214503");
        _verificaPin_verificaPinDatiDocumento.setCodDocumentoDipartimentale("CodDocumentoDipartimentale1699947335");
        _verificaPin_verificaPinDatiDocumento.setIdDocumentoIlec("IdDocumentoIlec289818913");
        _verificaPin_verificaPinDatiDocumento.setPin("Pin-1719801166");
        _verificaPin_verificaPin.setDatiDocumento(_verificaPin_verificaPinDatiDocumento);
        it.csi.dma.apiopsan.verificaservices.dmacc.VerificaPinResponse _verificaPin__return = port.verificaPin(_verificaPin_verificaPin);
        System.out.println("verificaPin.result=" + _verificaPin__return);


        }
        {
        System.out.println("Invoking verificaUtenteAbilitato...");
        it.csi.dma.apiopsan.verificaservices.dmacc.VerificaUtenteAbilitatoRequest _verificaUtenteAbilitato_verificaUtenteAbilitato = new it.csi.dma.apiopsan.verificaservices.dmacc.VerificaUtenteAbilitatoRequest();
        it.csi.dma.apiopsan.verificaservices.dma.RichiedenteInfo _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedente = new it.csi.dma.apiopsan.verificaservices.dma.RichiedenteInfo();
        it.csi.dma.apiopsan.verificaservices.dmacc.ApplicativoVerticale _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteApplicativoVerticale = new it.csi.dma.apiopsan.verificaservices.dmacc.ApplicativoVerticale();
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteApplicativoVerticale.setCodice("Codice1526883737");
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteApplicativoVerticale.setDescrizione("Descrizione430311515");
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedente.setApplicativoVerticale(_verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteApplicativoVerticale);
        it.csi.dma.apiopsan.verificaservices.dmacc.ApplicazioneRichiedente _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteApplicazione = new it.csi.dma.apiopsan.verificaservices.dmacc.ApplicazioneRichiedente();
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteApplicazione.setCodice("Codice1338306833");
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteApplicazione.setDescrizione("Descrizione-1394383478");
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedente.setApplicazione(_verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteApplicazione);
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedente.setCodiceFiscale("CodiceFiscale-1153840228");
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedente.setIp("Ip1598694970");
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedente.setNumeroTransazione("NumeroTransazione554932924");
        it.csi.dma.apiopsan.verificaservices.dma.Ruolo _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteRuolo = new it.csi.dma.apiopsan.verificaservices.dma.Ruolo();
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteRuolo.setCodice("Codice706020819");
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteRuolo.setDescrizione("Descrizione-1483486660");
        _verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedente.setRuolo(_verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedenteRuolo);
        _verificaUtenteAbilitato_verificaUtenteAbilitato.setRichiedente(_verificaUtenteAbilitato_verificaUtenteAbilitatoRichiedente);
        it.csi.dma.apiopsan.verificaservices.dmacc.VerificaUtenteAbilitatoResponse _verificaUtenteAbilitato__return = port.verificaUtenteAbilitato(_verificaUtenteAbilitato_verificaUtenteAbilitato);
        System.out.println("verificaUtenteAbilitato.result=" + _verificaUtenteAbilitato__return);


        }

        System.exit(0);
    }

}
