/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.ultimodocumentoservice.dmaccbl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-10-03T22:05:13.347+02:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://dmaccbl.csi.it/", name = "UltimoDocumentoService")
@XmlSeeAlso({ObjectFactory.class, it.csi.dma.apiopsan.ultimodocumentoservice.dma.ObjectFactory.class, it.csi.dma.apiopsan.ultimodocumentoservice.dmacc.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UltimoDocumentoService {

    @WebMethod
    @WebResult(name = "getUltimoDocumentoResponse", targetNamespace = "http://dmaccbl.csi.it/", partName = "getUltimoDocumentoResponse")
    public it.csi.dma.apiopsan.ultimodocumentoservice.dmacc.GetUltimoDocumentoResponse getUltimoDocumento(

        @WebParam(partName = "getUltimoDocumentoRequest", name = "getUltimoDocumentoRequest", targetNamespace = "http://dmaccbl.csi.it/")
        it.csi.dma.apiopsan.ultimodocumentoservice.dmacc.GetUltimoDocumentoRequest getUltimoDocumentoRequest
    );
}
