/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.consensoextservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-08-04T08:26:00.048+02:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "ConsensoINIExtService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ConsensoINIExtService {

    @WebMethod
    @WebResult(name = "statoConsensiResponse", targetNamespace = "http://dmacc.csi.it/", partName = "statoConsensiResponse")
    public StatoConsensiResponse statoConsensi(

        @WebParam(partName = "statoConsensi", name = "statoConsensi", targetNamespace = "http://dmacc.csi.it/")
        StatoConsensiExtRequeste statoConsensi
    );

    @WebMethod
    @WebResult(name = "comunicazioneConsensiResponse", targetNamespace = "http://dmacc.csi.it/", partName = "comunicazioneConsensiResponse")
    public ComunicazioneConsensiResponse comunicazioneConsensi(

        @WebParam(partName = "comunicazioneConsensi", name = "comunicazioneConsensi", targetNamespace = "http://dmacc.csi.it/")
        ComunicazioneConsensiExtRequeste comunicazioneConsensi
    );

    @WebMethod
    @WebResult(name = "recuperoInformativaResponse", targetNamespace = "http://dmacc.csi.it/", partName = "recuperoInformativaResponse")
    public RecuperoInformativaResponse recuperoInformativa(

        @WebParam(partName = "recuperoInformativa", name = "recuperoInformativa", targetNamespace = "http://dmacc.csi.it/")
        RecuperoInformativaExtRequeste recuperoInformativa
    );
}
