/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.consensoextservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-08-04T08:26:00.107+02:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "ConsensoINIExtService",
                  wsdlLocation = "file:/D:/ConsensoINIExtService.wsdl",
                  targetNamespace = "http://dmacc.csi.it/")
public class ConsensoINIExtService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "ConsensoINIExtService");
    public final static QName ConsensoINIExtServicePort = new QName("http://dmacc.csi.it/", "ConsensoINIExtServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/ConsensoINIExtService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsensoINIExtService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/ConsensoINIExtService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsensoINIExtService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsensoINIExtService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsensoINIExtService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ConsensoINIExtService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsensoINIExtService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsensoINIExtService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ConsensoINIExtService
     */
    @WebEndpoint(name = "ConsensoINIExtServicePort")
    public ConsensoINIExtService getConsensoINIExtServicePort() {
        return super.getPort(ConsensoINIExtServicePort, ConsensoINIExtService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsensoINIExtService
     */
    @WebEndpoint(name = "ConsensoINIExtServicePort")
    public ConsensoINIExtService getConsensoINIExtServicePort(WebServiceFeature... features) {
        return super.getPort(ConsensoINIExtServicePort, ConsensoINIExtService.class, features);
    }

}
