/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


package it.csi.dma.apiopsan.consensoextservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-08-04T10:54:49.230+02:00
 * Generated source version: 3.5.3
 *
 */
public final class ConsensoINIExtService_ConsensoINIExtServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://dmacc.csi.it/", "ConsensoINIExtService");

    private ConsensoINIExtService_ConsensoINIExtServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConsensoINIExtService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ConsensoINIExtService_Service ss = new ConsensoINIExtService_Service(wsdlURL, SERVICE_NAME);
        ConsensoINIExtService port = ss.getConsensoINIExtServicePort();

        {
        System.out.println("Invoking statoConsensi...");
        it.csi.dma.apiopsan.consensoextservice.StatoConsensiExtRequeste _statoConsensi_statoConsensi = null;
        it.csi.dma.apiopsan.consensoextservice.StatoConsensiResponse _statoConsensi__return = port.statoConsensi(_statoConsensi_statoConsensi);
        System.out.println("statoConsensi.result=" + _statoConsensi__return);


        }
        {
        System.out.println("Invoking comunicazioneConsensi...");
        it.csi.dma.apiopsan.consensoextservice.ComunicazioneConsensiExtRequeste _comunicazioneConsensi_comunicazioneConsensi = null;
        it.csi.dma.apiopsan.consensoextservice.ComunicazioneConsensiResponse _comunicazioneConsensi__return = port.comunicazioneConsensi(_comunicazioneConsensi_comunicazioneConsensi);
        System.out.println("comunicazioneConsensi.result=" + _comunicazioneConsensi__return);


        }
        {
        System.out.println("Invoking recuperoInformativa...");
        it.csi.dma.apiopsan.consensoextservice.RecuperoInformativaExtRequeste _recuperoInformativa_recuperoInformativa = null;
        it.csi.dma.apiopsan.consensoextservice.RecuperoInformativaResponse _recuperoInformativa__return = port.recuperoInformativa(_recuperoInformativa_recuperoInformativa);
        System.out.println("recuperoInformativa.result=" + _recuperoInformativa__return);


        }

        System.exit(0);
    }

}
