/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.taccuinoservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-29T12:11:09.602+02:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "TaccuinoServiceImplService",
                  wsdlLocation = "file:/D:/DOCUMENTI/CSI/TaccuinoService.wsdl",
                  targetNamespace = "http://dmaclbluc.dma.csi.it/")
public class TaccuinoServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmaclbluc.dma.csi.it/", "TaccuinoServiceImplService");
    public final static QName TaccuinoServicePort = new QName("http://dmaclbluc.dma.csi.it/", "TaccuinoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/DOCUMENTI/CSI/TaccuinoService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaccuinoServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/DOCUMENTI/CSI/TaccuinoService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TaccuinoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaccuinoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaccuinoServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TaccuinoServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TaccuinoServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TaccuinoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TaccuinoService
     */
    @WebEndpoint(name = "TaccuinoServicePort")
    public TaccuinoService getTaccuinoServicePort() {
        return super.getPort(TaccuinoServicePort, TaccuinoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaccuinoService
     */
    @WebEndpoint(name = "TaccuinoServicePort")
    public TaccuinoService getTaccuinoServicePort(WebServiceFeature... features) {
        return super.getPort(TaccuinoServicePort, TaccuinoService.class, features);
    }

}
