/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


package it.csi.dma.apiopsan.taccuinoservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-29T12:11:09.507+02:00
 * Generated source version: 3.5.3
 *
 */
public final class TaccuinoService_TaccuinoServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://dmaclbluc.dma.csi.it/", "TaccuinoServiceImplService");

    private TaccuinoService_TaccuinoServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TaccuinoServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TaccuinoServiceImplService ss = new TaccuinoServiceImplService(wsdlURL, SERVICE_NAME);
        TaccuinoService port = ss.getTaccuinoServicePort();

        {
        System.out.println("Invoking setDolore...");
        it.csi.dma.apiopsan.taccuinoservice.SetDoloreRequest _setDolore_setDolore = null;
        it.csi.dma.apiopsan.taccuinoservice.SetDoloreResponse _setDolore__return = port.setDolore(_setDolore_setDolore);
        System.out.println("setDolore.result=" + _setDolore__return);


        }
        {
        System.out.println("Invoking setNotaGenerale...");
        it.csi.dma.apiopsan.taccuinoservice.SetNotaGeneraleRequest _setNotaGenerale_setNotaGenerale = null;
        it.csi.dma.apiopsan.taccuinoservice.SetNotaGeneraleResponse _setNotaGenerale__return = port.setNotaGenerale(_setNotaGenerale_setNotaGenerale);
        System.out.println("setNotaGenerale.result=" + _setNotaGenerale__return);


        }
        {
        System.out.println("Invoking getRilevazioni...");
        it.csi.dma.apiopsan.taccuinoservice.GetRilevazioniRequest _getRilevazioni_getRilevazioni = null;
        it.csi.dma.apiopsan.taccuinoservice.GetRilevazioniResponse _getRilevazioni__return = port.getRilevazioni(_getRilevazioni_getRilevazioni);
        System.out.println("getRilevazioni.result=" + _getRilevazioni__return);


        }
        {
        System.out.println("Invoking setDieta...");
        it.csi.dma.apiopsan.taccuinoservice.SetDietaRequest _setDieta_setDieta = null;
        it.csi.dma.apiopsan.taccuinoservice.SetDietaResponse _setDieta__return = port.setDieta(_setDieta_setDieta);
        System.out.println("setDieta.result=" + _setDieta__return);


        }
        {
        System.out.println("Invoking getDolori...");
        it.csi.dma.apiopsan.taccuinoservice.GetDoloriRequest _getDolori_getDolori = null;
        it.csi.dma.apiopsan.taccuinoservice.GetDoloriResponse _getDolori__return = port.getDolori(_getDolori_getDolori);
        System.out.println("getDolori.result=" + _getDolori__return);


        }
        {
        System.out.println("Invoking setImpostazioniTaccuino...");
        it.csi.dma.apiopsan.taccuinoservice.SetImpostazioniTaccuinoRequest _setImpostazioniTaccuino_setImpostazioniTaccuino = null;
        it.csi.dma.apiopsan.taccuinoservice.SetImpostazioniTaccuinoResponse _setImpostazioniTaccuino__return = port.setImpostazioniTaccuino(_setImpostazioniTaccuino_setImpostazioniTaccuino);
        System.out.println("setImpostazioniTaccuino.result=" + _setImpostazioniTaccuino__return);


        }
        {
        System.out.println("Invoking setFarmaco...");
        it.csi.dma.apiopsan.taccuinoservice.SetFarmacoRequest _setFarmaco_setFarmaco = null;
        it.csi.dma.apiopsan.taccuinoservice.SetFarmacoResponse _setFarmaco__return = port.setFarmaco(_setFarmaco_setFarmaco);
        System.out.println("setFarmaco.result=" + _setFarmaco__return);


        }
        {
        System.out.println("Invoking setSintomo...");
        it.csi.dma.apiopsan.taccuinoservice.SetSintomoRequest _setSintomo_setSintomo = null;
        it.csi.dma.apiopsan.taccuinoservice.SetSintomoResponse _setSintomo__return = port.setSintomo(_setSintomo_setSintomo);
        System.out.println("setSintomo.result=" + _setSintomo__return);


        }
        {
        System.out.println("Invoking cancellaContattiStrutture...");
        it.csi.dma.apiopsan.taccuinoservice.CancellaContattiStruttureRequest _cancellaContattiStrutture_cancellaContattiStrutture = null;
        it.csi.dma.apiopsan.taccuinoservice.CancellaContattiStruttureResponse _cancellaContattiStrutture__return = port.cancellaContattiStrutture(_cancellaContattiStrutture_cancellaContattiStrutture);
        System.out.println("cancellaContattiStrutture.result=" + _cancellaContattiStrutture__return);


        }
        {
        System.out.println("Invoking setRilevazioni...");
        it.csi.dma.apiopsan.taccuinoservice.SetRilevazioniRequest _setRilevazioni_setRilevazioni = null;
        it.csi.dma.apiopsan.taccuinoservice.SetRilevazioniResponse _setRilevazioni__return = port.setRilevazioni(_setRilevazioni_setRilevazioni);
        System.out.println("setRilevazioni.result=" + _setRilevazioni__return);


        }
        {
        System.out.println("Invoking getDiete...");
        it.csi.dma.apiopsan.taccuinoservice.GetDieteRequest _getDiete_getDiete = null;
        it.csi.dma.apiopsan.taccuinoservice.GetDieteResponse _getDiete__return = port.getDiete(_getDiete_getDiete);
        System.out.println("getDiete.result=" + _getDiete__return);


        }
        {
        System.out.println("Invoking setOscuramentoTaccuino...");
        it.csi.dma.apiopsan.taccuinoservice.SetOscuramentoTaccuinoRequest _setOscuramentoTaccuino_setOscuramentoTaccuino = null;
        it.csi.dma.apiopsan.taccuinoservice.SetOscuramentoTaccuinoResponse _setOscuramentoTaccuino__return = port.setOscuramentoTaccuino(_setOscuramentoTaccuino_setOscuramentoTaccuino);
        System.out.println("setOscuramentoTaccuino.result=" + _setOscuramentoTaccuino__return);


        }
        {
        System.out.println("Invoking getDecodificaStrutturaTipo...");
        it.csi.dma.apiopsan.taccuinoservice.GetDecodificaStrutturaTipoRequest _getDecodificaStrutturaTipo_getDecodificaStrutturaTipo = null;
        it.csi.dma.apiopsan.taccuinoservice.GetDecodificaStrutturaTipoResponse _getDecodificaStrutturaTipo__return = port.getDecodificaStrutturaTipo(_getDecodificaStrutturaTipo_getDecodificaStrutturaTipo);
        System.out.println("getDecodificaStrutturaTipo.result=" + _getDecodificaStrutturaTipo__return);


        }
        {
        System.out.println("Invoking cancellaSintomi...");
        it.csi.dma.apiopsan.taccuinoservice.CancellaSintomiRequest _cancellaSintomi_cancellaSintomi = null;
        it.csi.dma.apiopsan.taccuinoservice.CancellaSintomiResponse _cancellaSintomi__return = port.cancellaSintomi(_cancellaSintomi_cancellaSintomi);
        System.out.println("cancellaSintomi.result=" + _cancellaSintomi__return);


        }
        {
        System.out.println("Invoking getTaccuino...");
        it.csi.dma.apiopsan.taccuinoservice.GetTaccuinoRequest _getTaccuino_getTaccuino = null;
        it.csi.dma.apiopsan.taccuinoservice.GetTaccuinoResponse _getTaccuino__return = port.getTaccuino(_getTaccuino_getTaccuino);
        System.out.println("getTaccuino.result=" + _getTaccuino__return);


        }
        {
        System.out.println("Invoking setContattoStruttura...");
        it.csi.dma.apiopsan.taccuinoservice.SetContattoStrutturaRequest _setContattoStruttura_setContattoStruttura = null;
        it.csi.dma.apiopsan.taccuinoservice.SetContattoStrutturaResponse _setContattoStruttura__return = port.setContattoStruttura(_setContattoStruttura_setContattoStruttura);
        System.out.println("setContattoStruttura.result=" + _setContattoStruttura__return);


        }
        {
        System.out.println("Invoking getDecodificaModalitaRilevazione...");
        it.csi.dma.apiopsan.taccuinoservice.GetDecodificaModalitaRilevazioneRequest _getDecodificaModalitaRilevazione_getDecodificaModalitaRilevazione = null;
        it.csi.dma.apiopsan.taccuinoservice.GetDecodificheModalitaRilevazioneResponse _getDecodificaModalitaRilevazione__return = port.getDecodificaModalitaRilevazione(_getDecodificaModalitaRilevazione_getDecodificaModalitaRilevazione);
        System.out.println("getDecodificaModalitaRilevazione.result=" + _getDecodificaModalitaRilevazione__return);


        }
        {
        System.out.println("Invoking cancellaRilevazioni...");
        it.csi.dma.apiopsan.taccuinoservice.CancellaRilevazioniRequest _cancellaRilevazioni_cancellaRilevazioni = null;
        it.csi.dma.apiopsan.taccuinoservice.CancellaRilevazioniResponse _cancellaRilevazioni__return = port.cancellaRilevazioni(_cancellaRilevazioni_cancellaRilevazioni);
        System.out.println("cancellaRilevazioni.result=" + _cancellaRilevazioni__return);


        }
        {
        System.out.println("Invoking getContattiStrutture...");
        it.csi.dma.apiopsan.taccuinoservice.GetContattiStruttureRequest _getContattiStrutture_getContattiStrutture = null;
        it.csi.dma.apiopsan.taccuinoservice.GetContattiStruttureResponse _getContattiStrutture__return = port.getContattiStrutture(_getContattiStrutture_getContattiStrutture);
        System.out.println("getContattiStrutture.result=" + _getContattiStrutture__return);


        }
        {
        System.out.println("Invoking getEventi...");
        it.csi.dma.apiopsan.taccuinoservice.GetEventiRequest _getEventi_getEventi = null;
        it.csi.dma.apiopsan.taccuinoservice.GetEventiResponse _getEventi__return = port.getEventi(_getEventi_getEventi);
        System.out.println("getEventi.result=" + _getEventi__return);


        }
        {
        System.out.println("Invoking cancellaEvento...");
        it.csi.dma.apiopsan.taccuinoservice.CancellaEventoRequest _cancellaEvento_cancellaEvento = null;
        it.csi.dma.apiopsan.taccuinoservice.CancellaEventoResponse _cancellaEvento__return = port.cancellaEvento(_cancellaEvento_cancellaEvento);
        System.out.println("cancellaEvento.result=" + _cancellaEvento__return);


        }
        {
        System.out.println("Invoking cancellaFarmaco...");
        it.csi.dma.apiopsan.taccuinoservice.CancellaFarmacoRequest _cancellaFarmaco_cancellaFarmaco = null;
        it.csi.dma.apiopsan.taccuinoservice.CancellaFarmacoResponse _cancellaFarmaco__return = port.cancellaFarmaco(_cancellaFarmaco_cancellaFarmaco);
        System.out.println("cancellaFarmaco.result=" + _cancellaFarmaco__return);


        }
        {
        System.out.println("Invoking getFarmaci...");
        it.csi.dma.apiopsan.taccuinoservice.GetFarmaciRequest _getFarmaci_getFarmaci = null;
        it.csi.dma.apiopsan.taccuinoservice.GetFarmaciResponse _getFarmaci__return = port.getFarmaci(_getFarmaci_getFarmaci);
        System.out.println("getFarmaci.result=" + _getFarmaci__return);


        }
        {
        System.out.println("Invoking getSintomi...");
        it.csi.dma.apiopsan.taccuinoservice.GetSintomiRequest _getSintomi_getSintomi = null;
        it.csi.dma.apiopsan.taccuinoservice.GetSintomiResponse _getSintomi__return = port.getSintomi(_getSintomi_getSintomi);
        System.out.println("getSintomi.result=" + _getSintomi__return);


        }
        {
        System.out.println("Invoking getDecodificaIntensitaDolore...");
        it.csi.dma.apiopsan.taccuinoservice.GetDecodificaIntensitaDoloreRequest _getDecodificaIntensitaDolore_getDecodificaIntensitaDolore = null;
        it.csi.dma.apiopsan.taccuinoservice.GetDecodificaIntensitaDoloreResponse _getDecodificaIntensitaDolore__return = port.getDecodificaIntensitaDolore(_getDecodificaIntensitaDolore_getDecodificaIntensitaDolore);
        System.out.println("getDecodificaIntensitaDolore.result=" + _getDecodificaIntensitaDolore__return);


        }
        {
        System.out.println("Invoking cancellaDolori...");
        it.csi.dma.apiopsan.taccuinoservice.CancellaDoloriRequest _cancellaDolori_cancellaDolori = null;
        it.csi.dma.apiopsan.taccuinoservice.CancellaDoloriResponse _cancellaDolori__return = port.cancellaDolori(_cancellaDolori_cancellaDolori);
        System.out.println("cancellaDolori.result=" + _cancellaDolori__return);


        }
        {
        System.out.println("Invoking getDescrittoriMisurazione...");
        it.csi.dma.apiopsan.taccuinoservice.GetDescrittoriMisurazioneRequest _getDescrittoriMisurazione_getDescrittoriMisurazione = null;
        it.csi.dma.apiopsan.taccuinoservice.GetDescrittoriMisurazioneResponse _getDescrittoriMisurazione__return = port.getDescrittoriMisurazione(_getDescrittoriMisurazione_getDescrittoriMisurazione);
        System.out.println("getDescrittoriMisurazione.result=" + _getDescrittoriMisurazione__return);


        }
        {
        System.out.println("Invoking getLog...");
        it.csi.dma.apiopsan.taccuinoservice.DmaclLXmlMessaggiDto _getLog_getLog = null;
        try {
            it.csi.dma.apiopsan.taccuinoservice.DmaclLXmlMessaggiDtoArray _getLog__return = port.getLog(_getLog_getLog);
            System.out.println("getLog.result=" + _getLog__return);

        } catch (DmaclLXmlMessaggiDaoException_Exception e) {
            System.out.println("Expected exception: DmaclLXmlMessaggiDaoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getDecodificaContattoTipo...");
        it.csi.dma.apiopsan.taccuinoservice.GetDecodificaContattoTipoRequest _getDecodificaContattoTipo_getDecodificaContattoTipo = null;
        it.csi.dma.apiopsan.taccuinoservice.GetDecodificaContattoTipoResponse _getDecodificaContattoTipo__return = port.getDecodificaContattoTipo(_getDecodificaContattoTipo_getDecodificaContattoTipo);
        System.out.println("getDecodificaContattoTipo.result=" + _getDecodificaContattoTipo__return);


        }
        {
        System.out.println("Invoking setEvento...");
        it.csi.dma.apiopsan.taccuinoservice.SetEventoRequest _setEvento_setEvento = null;
        it.csi.dma.apiopsan.taccuinoservice.SetEventoResponse _setEvento__return = port.setEvento(_setEvento_setEvento);
        System.out.println("setEvento.result=" + _setEvento__return);


        }
        {
        System.out.println("Invoking cancellaDieta...");
        it.csi.dma.apiopsan.taccuinoservice.CancellaDietaRequest _cancellaDieta_cancellaDieta = null;
        it.csi.dma.apiopsan.taccuinoservice.CancellaDietaResponse _cancellaDieta__return = port.cancellaDieta(_cancellaDieta_cancellaDieta);
        System.out.println("cancellaDieta.result=" + _cancellaDieta__return);


        }

        System.exit(0);
    }

}
