/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.csi.dma.apiopsan.scaricorefertoservice.dmaccbl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import it.csi.dma.apiopsan.scaricorefertoservice.dmacc.ImpostaDataRitiroRefertoSRResponse;

/**
 * This class was generated by Apache CXF 2.2.7
 * Wed Sep 14 15:36:17 CEST 2022
 * Generated source version: 2.2.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "ScaricoRefertoService",
                      portName = "ScaricoRefertoServicePort",
                      targetNamespace = "http://dmaccbl.csi.it/",
                      //wsdlLocation = "https://tst-bejava-dma.isan.csi.it/dmaccrti/ScaricoRefertoService?wsdl",
                      endpointInterface = "it.csi.dma.apiopsan.scaricorefertoservice.dmaccbl.ScaricoRefertoService")
                      
public class ScaricoRefertoServiceImpl implements ScaricoRefertoService {

    private static final Logger LOG = Logger.getLogger(ScaricoRefertoServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see it.csi.dmaccbl.ScaricoRefertoService#getCLDaContattareSR(it.csi.dmaccbl.GetCLDaContattareSR  getCLDaContattareSR )*
     */
    public GetCLDaContattareSRResponse getCLDaContattareSR(GetCLDaContattareSR getCLDaContattareSR) { 
        LOG.info("Executing operation getCLDaContattareSR");
        System.out.println(getCLDaContattareSR);
        try {
            GetCLDaContattareSRResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.dmaccbl.ScaricoRefertoService#checkGetRefertoSR(it.csi.dmaccbl.CheckGetRefertoSR  checkGetRefertoSR )*
     */
    public CheckGetRefertoSRResponse checkGetRefertoSR(CheckGetRefertoSR checkGetRefertoSR) { 
        LOG.info("Executing operation checkGetRefertoSR");
        System.out.println(checkGetRefertoSR);
        try {
            CheckGetRefertoSRResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.dmaccbl.ScaricoRefertoService#addPageQRCode(it.csi.dmaccbl.AddPageQRCodeRequest  addPageQRCode )*
     */
    public AddPageQRCodeResponse addPageQRCode(AddPageQRCodeRequest addPageQRCode) { 
        LOG.info("Executing operation addPageQRCode");
        System.out.println(addPageQRCode);
        try {
            AddPageQRCodeResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.dmaccbl.ScaricoRefertoService#scansionaRefertoQRCode(it.csi.dmaccbl.ScansionaRefertoQRCodeRequest  scansionaRefertoQRCode )*
     */
    public ScansionaRefertoQRCodeResponse scansionaRefertoQRCode(ScansionaRefertoQRCodeRequest scansionaRefertoQRCode) { 
        LOG.info("Executing operation scansionaRefertoQRCode");
        System.out.println(scansionaRefertoQRCode);
        try {
            ScansionaRefertoQRCodeResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.dmaccbl.ScaricoRefertoService#checkVerificaDelega(it.csi.dmaccbl.CheckVerificaDelega  checkVerificaDelega )*
     */
    public CheckVerificaDelegaResponse checkVerificaDelega(CheckVerificaDelega checkVerificaDelega) { 
        LOG.info("Executing operation checkVerificaDelega");
        System.out.println(checkVerificaDelega);
        try {
            CheckVerificaDelegaResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.dmaccbl.ScaricoRefertoService#impostaDataRitiroRefertoSR(it.csi.dmaccbl.ImpostaDataRitiroRefertoSRRequest  impostaDataRitiroRefertoSR )*
     */
    public ImpostaDataRitiroRefertoSRResponse impostaDataRitiroRefertoSR(ImpostaDataRitiroRefertoSRRequest impostaDataRitiroRefertoSR) { 
        LOG.info("Executing operation impostaDataRitiroRefertoSR");
        System.out.println(impostaDataRitiroRefertoSR);
        try {
           ImpostaDataRitiroRefertoSRResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
