/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.scaricorefertoservice.dmaccbl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import it.csi.dma.apiopsan.scaricorefertoservice.dmacc.ImpostaDataRitiroRefertoSRResponse;

/**
 * This class was generated by Apache CXF 2.2.7
 * Wed Sep 14 15:36:17 CEST 2022
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "http://dmaccbl.csi.it/", name = "ScaricoRefertoService")
@XmlSeeAlso({ObjectFactory.class,ObjectFactory.class,ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ScaricoRefertoService {

    @WebMethod
    @WebResult(name = "getCLDaContattareSRResponse", targetNamespace = "http://dmaccbl.csi.it/", partName = "getCLDaContattareSRResponse")
    public GetCLDaContattareSRResponse getCLDaContattareSR(
        @WebParam(partName = "getCLDaContattareSR", name = "getCLDaContattareSR", targetNamespace = "http://dmaccbl.csi.it/")
        GetCLDaContattareSR getCLDaContattareSR
    );

    @WebMethod
    @WebResult(name = "checkGetRefertoSRResponse", targetNamespace = "http://dmaccbl.csi.it/", partName = "checkGetRefertoSRResponse")
    public CheckGetRefertoSRResponse checkGetRefertoSR(
        @WebParam(partName = "checkGetRefertoSR", name = "checkGetRefertoSR", targetNamespace = "http://dmaccbl.csi.it/")
        CheckGetRefertoSR checkGetRefertoSR
    );

    @WebMethod
    @WebResult(name = "addPageQRCodeResponse", targetNamespace = "http://dmaccbl.csi.it/", partName = "addPageQRCodeResponse")
    public AddPageQRCodeResponse addPageQRCode(
        @WebParam(partName = "addPageQRCode", name = "addPageQRCode", targetNamespace = "http://dmaccbl.csi.it/")
        AddPageQRCodeRequest addPageQRCode
    );

    @WebMethod
    @WebResult(name = "scansionaRefertoQRCodeResponse", targetNamespace = "http://dmaccbl.csi.it/", partName = "scansionaRefertoQRCodeResponse")
    public ScansionaRefertoQRCodeResponse scansionaRefertoQRCode(
        @WebParam(partName = "scansionaRefertoQRCode", name = "scansionaRefertoQRCode", targetNamespace = "http://dmaccbl.csi.it/")
        ScansionaRefertoQRCodeRequest scansionaRefertoQRCode
    );

    @WebMethod
    @WebResult(name = "checkVerificaDelegaResponse", targetNamespace = "http://dmaccbl.csi.it/", partName = "checkVerificaDelegaResponse")
    public CheckVerificaDelegaResponse checkVerificaDelega(
        @WebParam(partName = "checkVerificaDelega", name = "checkVerificaDelega", targetNamespace = "http://dmaccbl.csi.it/")
        CheckVerificaDelega checkVerificaDelega
    );

    @WebMethod
    @WebResult(name = "impostaDataRitiroRefertoSRResponse", targetNamespace = "http://dmaccbl.csi.it/", partName = "impostaDataRitiroRefertoSRResponse")
    public ImpostaDataRitiroRefertoSRResponse impostaDataRitiroRefertoSR(
        @WebParam(partName = "impostaDataRitiroRefertoSR", name = "impostaDataRitiroRefertoSR", targetNamespace = "http://dmaccbl.csi.it/")
        ImpostaDataRitiroRefertoSRRequest impostaDataRitiroRefertoSR
    );
}
