/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.tokeninformation.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-10-29T18:45:38.509+02:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "TokenInformationService")
@XmlSeeAlso({it.csi.dma.apiopsan.tokeninformation.dmac.ObjectFactory.class, it.csi.dma.apiopsan.tokeninformation.dmaccbl.ObjectFactory.class, it.csi.dma.apiopsan.tokeninformation.dma.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TokenInformationService {

    @WebMethod(action = "http://dmaccbl.csi.it/getTokenInformation2")
    @WebResult(name = "getTokenInformation2Response", targetNamespace = "http://dmacc.csi.it/", partName = "getTokenInformation2Response")
    public GetTokenInformation2Response getTokenInformation2(

        @WebParam(partName = "getTokenInformation2Request", name = "getTokenInformation2Request", targetNamespace = "http://dmaccbl.csi.it/")
        GetTokenInformation2Request getTokenInformation2Request
    );

    @WebMethod(action = "http://dmaccbl.csi.it/getTokenInformation")
    @WebResult(name = "getTokenInformationResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getTokenInformationResponse")
    public GetTokenInformationResponse getTokenInformation(

        @WebParam(partName = "getTokenInformationRequest", name = "getTokenInformationRequest", targetNamespace = "http://dmaccbl.csi.it/")
        GetTokenInformationRequest getTokenInformationRequest
    );
}
