/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.ricercadocumentiiniservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2023-05-09T16:38:43.176+02:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "RicercaDocumentiINIService")
@XmlSeeAlso({ObjectFactory.class, it.csi.dma.apiopsan.ricercadocumentiiniservice.fse.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RicercaDocumentiINIService {

    @WebMethod
    @WebResult(name = "ricercaDocumentiResponse", targetNamespace = "http://dmacc.csi.it/", partName = "ricercaDocumentiResponse")
    public RicercaDocumentiResponse ricercaDocumenti(

        @WebParam(partName = "ricercaDocumenti", name = "ricercaDocumenti", targetNamespace = "http://dmacc.csi.it/")
        RicercaDocumentiRequeste ricercaDocumenti
    );
}
