/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.ricercadocumentiiniservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2023-05-09T16:38:43.209+02:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "RicercaDocumentiINIService",
                  wsdlLocation = "https://tst-bejava-dma.isan.csi.it/dmaccrti/RicercaDocumentiINIService?wsdl",
                  targetNamespace = "http://dmacc.csi.it/")
public class RicercaDocumentiINIService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "RicercaDocumentiINIService");
    public final static QName RicercaDocumentiINIServicePort = new QName("http://dmacc.csi.it/", "RicercaDocumentiINIServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://tst-bejava-dma.isan.csi.it/dmaccrti/RicercaDocumentiINIService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RicercaDocumentiINIService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://tst-bejava-dma.isan.csi.it/dmaccrti/RicercaDocumentiINIService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RicercaDocumentiINIService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RicercaDocumentiINIService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RicercaDocumentiINIService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RicercaDocumentiINIService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RicercaDocumentiINIService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RicercaDocumentiINIService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RicercaDocumentiINIService
     */
    @WebEndpoint(name = "RicercaDocumentiINIServicePort")
    public RicercaDocumentiINIService getRicercaDocumentiINIServicePort() {
        return super.getPort(RicercaDocumentiINIServicePort, RicercaDocumentiINIService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RicercaDocumentiINIService
     */
    @WebEndpoint(name = "RicercaDocumentiINIServicePort")
    public RicercaDocumentiINIService getRicercaDocumentiINIServicePort(WebServiceFeature... features) {
        return super.getPort(RicercaDocumentiINIServicePort, RicercaDocumentiINIService.class, features);
    }

}
