/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.documentiservice.dmacc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-05T16:50:08.196+02:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "DocumentiService",
                  wsdlLocation = "file:../DocumentiService.wsdl",
                  targetNamespace = "http://dmacc.csi.it/")
public class DocumentiService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "DocumentiService");
    public final static QName DocumentiServicePort = new QName("http://dmacc.csi.it/", "DocumentiServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:../DocumentiService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DocumentiService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:../DocumentiService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DocumentiService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DocumentiService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentiService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DocumentiService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DocumentiService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DocumentiService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DocumentiService
     */
    @WebEndpoint(name = "DocumentiServicePort")
    public DocumentiService getDocumentiServicePort() {
        return super.getPort(DocumentiServicePort, DocumentiService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentiService
     */
    @WebEndpoint(name = "DocumentiServicePort")
    public DocumentiService getDocumentiServicePort(WebServiceFeature... features) {
        return super.getPort(DocumentiServicePort, DocumentiService.class, features);
    }

}
