/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.accodarichiestetrasferimentoindiceservice.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-13T16:10:46.082+02:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "AccodaRichiesteTrasferimentoIndiceService")
@XmlSeeAlso({it.csi.dma.apiopsan.accodarichiestetrasferimentoindiceservice.dma.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AccodaRichiesteTrasferimentoIndiceService {

    @WebMethod
    @WebResult(name = "accodaRichiesteTrasferimentoIndiceResponse", targetNamespace = "http://dmacc.csi.it/", partName = "accodaRichiesteTrasferimentoIndiceResponse")
    public AccodaRichiesteTrasferimentoIndiceResponse accodaRichiesteTrasferimentoIndice(

        @WebParam(partName = "accodaRichiesteTrasferimentoIndice", name = "accodaRichiesteTrasferimentoIndice", targetNamespace = "http://dmacc.csi.it/")
        AccodaRichiesteTrasferimentoIndice accodaRichiesteTrasferimentoIndice
    );
}
