/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.accodarichiestetrasferimentoindiceservice.dmacc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-13T16:10:46.125+02:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "AccodaRichiesteTrasferimentoIndiceService",
                  wsdlLocation = "file:/C:/axis-1_4/aa.wsdl",
                  targetNamespace = "http://dmacc.csi.it/")
public class AccodaRichiesteTrasferimentoIndiceService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "AccodaRichiesteTrasferimentoIndiceService");
    public final static QName AccodaRichiesteTrasferimentoIndiceServicePort = new QName("http://dmacc.csi.it/", "AccodaRichiesteTrasferimentoIndiceServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/axis-1_4/aa.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccodaRichiesteTrasferimentoIndiceService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/axis-1_4/aa.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccodaRichiesteTrasferimentoIndiceService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccodaRichiesteTrasferimentoIndiceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccodaRichiesteTrasferimentoIndiceService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AccodaRichiesteTrasferimentoIndiceService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AccodaRichiesteTrasferimentoIndiceService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AccodaRichiesteTrasferimentoIndiceService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AccodaRichiesteTrasferimentoIndiceService
     */
    @WebEndpoint(name = "AccodaRichiesteTrasferimentoIndiceServicePort")
    public AccodaRichiesteTrasferimentoIndiceService getAccodaRichiesteTrasferimentoIndiceServicePort() {
        return super.getPort(AccodaRichiesteTrasferimentoIndiceServicePort, AccodaRichiesteTrasferimentoIndiceService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccodaRichiesteTrasferimentoIndiceService
     */
    @WebEndpoint(name = "AccodaRichiesteTrasferimentoIndiceServicePort")
    public AccodaRichiesteTrasferimentoIndiceService getAccodaRichiesteTrasferimentoIndiceServicePort(WebServiceFeature... features) {
        return super.getPort(AccodaRichiesteTrasferimentoIndiceServicePort, AccodaRichiesteTrasferimentoIndiceService.class, features);
    }

}
