/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.recuperadocumentoservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-22T06:16:58.170+02:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "RecuperoDocumentoINIService",
                  wsdlLocation = "https://tst-bejava-dma.isan.csi.it/dmaccrti/RecuperoDocumentoINIService?wsdl",
                  targetNamespace = "http://dmacc.csi.it/")
public class RecuperoDocumentoINIService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "RecuperoDocumentoINIService");
    public final static QName RecuperoDocumentoINIServicePort = new QName("http://dmacc.csi.it/", "RecuperoDocumentoINIServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://tst-bejava-dma.isan.csi.it/dmaccrti/RecuperoDocumentoINIService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RecuperoDocumentoINIService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://tst-bejava-dma.isan.csi.it/dmaccrti/RecuperoDocumentoINIService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RecuperoDocumentoINIService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecuperoDocumentoINIService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecuperoDocumentoINIService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RecuperoDocumentoINIService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RecuperoDocumentoINIService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RecuperoDocumentoINIService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RecuperoDocumentoINIService
     */
    @WebEndpoint(name = "RecuperoDocumentoINIServicePort")
    public RecuperoDocumentoINIService getRecuperoDocumentoINIServicePort() {
        return super.getPort(RecuperoDocumentoINIServicePort, RecuperoDocumentoINIService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecuperoDocumentoINIService
     */
    @WebEndpoint(name = "RecuperoDocumentoINIServicePort")
    public RecuperoDocumentoINIService getRecuperoDocumentoINIServicePort(WebServiceFeature... features) {
        return super.getPort(RecuperoDocumentoINIServicePort, RecuperoDocumentoINIService.class, features);
    }

}
