/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.recuperadocumentoservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-22T06:16:58.070+02:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "RecuperoDocumentoINIService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RecuperoDocumentoINIService {

    @WebMethod
    @WebResult(name = "recuperoDocumentoResponse", targetNamespace = "http://dmacc.csi.it/", partName = "recuperoDocumentoResponse")
    public RecuperoDocumentoResponse recuperoDocumento(

        @WebParam(partName = "recuperoDocumento", name = "recuperoDocumento", targetNamespace = "http://dmacc.csi.it/")
        RecuperoDocumentoRequeste recuperoDocumento
    );
}
