/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


package it.csi.dma.apiopsan.screeningservice.dmacc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.7
 * Wed Sep 14 14:45:37 CEST 2022
 * Generated source version: 2.2.7
 * 
 */

public final class ScreeningService_ScreeningServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://dmacc.csi.it/", "ScreeningService");

    private ScreeningService_ScreeningServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ScreeningService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ScreeningService_Service ss = new ScreeningService_Service(wsdlURL, SERVICE_NAME);
        ScreeningService port = ss.getScreeningServicePort();  
        
        {
        System.out.println("Invoking getScreening...");
        it.csi.dma.apiopsan.screeningservice.dmacc.ScreeningRequest _getScreening_getScreening = null;
        it.csi.dma.apiopsan.screeningservice.dmacc.ScreeningResponse _getScreening__return = port.getScreening(_getScreening_getScreening);
        System.out.println("getScreening.result=" + _getScreening__return);


        }

        System.exit(0);
    }

}
