/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsan.screeningservice.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.7
 * Wed Sep 14 14:45:37 CEST 2022
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "ScreeningService")
@XmlSeeAlso({it.csi.dma.apiopsan.screeningservice.dmacc.ObjectFactory.class,ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ScreeningService {

    @WebMethod
    @WebResult(name = "getScreeningResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getScreeningResponse")
    public ScreeningResponse getScreening(
        @WebParam(partName = "getScreening", name = "getScreening", targetNamespace = "http://dmacc.csi.it/")
        ScreeningRequest getScreening
    );
}
